### ISSUE TITLE
Create a unit test that validates format of signature matrix and dataset

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/decomprolute#121]
Currently we test for the validation of data download but don't test the fidelity of the data. We need to determine what is required to run and then test for that.  I think Song has the best knowledge of what causes things to fail, and Anna has the unit test expertise, so am assigning you both.

**Comment by annapamma** [comment]
@LifeWorks When you get a chance, can you jot down a checklist of requirements for the data sets and signature matrices?

For example, something like...

Signature matrix must:
- have at least 1 gene for each signature

etc.

**Comment by LifeWorks** [comment]
> @LifeWorks When you get a chance, can you jot down a checklist of requirements for the data sets and signature matrices?
> 
> For example, something like...
> 
> Signature matrix must:
> 
> * have at least 1 gene for each signature
> 
> etc.

The signature matrix:
- rows are genes 
- columns are cell types
- row numbers should be (ideally much) larger than column numbers
- Each cell type ideally should have some genes that are more expressed than other cell types

The data:
- rows are all the genes
- columns are samples
- ideally, row names should contain all row names in the signature matrix
