### ISSUE TITLE
Xcell docker image not building on circleci

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/decomprolute#188]
I got the xcell docker image to build correctly, but it's still not building on circleCI. @LifeWorks @annapamma do either of you know what's happening? I commented out many lines and it's still not working.

**Comment by LifeWorks** [comment]
I thought all the deconvolution algorithms are not built automatically. Last time I checked that these algorithm dockers were not updated for months.

**Comment by sgosline** [comment]
Hmm, I'm only getting an error from the xcell one.

**Comment by LifeWorks** [comment]
My information might be outdated.

**Comment by sgosline** [comment]
Ok, I created some github actions to build the docker images in #189 (i apologize the issue name is off)

**Comment by annapamma** [comment]
Hi Sara,

It might just be an issue of it building on a VM versus a real computer.

I'll test it on my machine.
